Module7 task1
htmlacademy-react/2069403-six-cities-simple-11 pull request #10
Opened 2022-11-21 01:52 UTC by Yustes88

2022-11-22 03:03 UTC, Yustes88 commented on project/src/pages/room/room.tsx
> +                <CardsList offers={nearbyOffers} onListItemEnter={onListItemEnter} cardType = {'nearby'}/>
не могу решить проблему с маркерами, перестал отображаться изначально выбранный оффер при первом переходе с главной страницы (потому что в onListItemEnter я положила nearbyOffers), а после перехода на оффер из списка поблизости подсвечиваются сразу 2 маркера
я пробовала положить все в один лист (offersNearby.push(offer), но не получалось
![2022-11-22_09-56-38](https://user-images.githubusercontent.com/105499816/203210176-df19c029-c945-46ae-a026-d01a07ff5012.png)

2022-11-22 05:09 UTC, yurylavrukhin commented on project/src/pages/room/room.tsx
> +                <CardsList offers={nearbyOffers} onListItemEnter={onListItemEnter} cardType = {'nearby'}/>
1. на странице оффера нет логики с подсветкой при наведении, удали её
2. нужно показать на карте 4 маркера: 3 оффера поблизости + 1 подсвеченный текущий оффер (тот оффер, на страничке которого мы находимся)


> https://up.htmlacademy.ru/react/11/project/six-cities-simple#offerPage

2022-11-22 05:14 UTC, yurylavrukhin commented on project/src/pages/room/room.tsx
> +                <CardsList offers={nearbyOffers} onListItemEnter={onListItemEnter} cardType = {'nearby'}/>
можешь сделать массив офферов поблизости и текущего оффера spread'ом `let offers = [...offersNearby, currentOffer]`

2022-11-22 12:24 UTC, yurylavrukhin requested changes
Получилось хорошо ✨ Ты молодец!

<img width="1677" alt="image" src="https://user-images.githubusercontent.com/26966797/203313098-05574d21-8a20-4cab-83d4-c93516c7f011.png">
высоту карты бы поправить на странице оффера

2022-11-22 12:24 UTC, yurylavrukhin commented on project/src/pages/room/room.tsx
> +  const fullOffers = [...nearbyOffers, offer] as Offers;
тут можно обойтись без `as`

[если оффер не найден и isOfferLoading - false] — редиректи на 404

2022-11-22 12:24 UTC, yurylavrukhin commented on project/src/pages/room/room.tsx
> +    store.dispatch(fetchReviewsAction(Number(id)));
если в сторе уже есть этот оффер — нам его незачем загружать, можем взять из стора.

давай сделаем здесь проверку на существования оффера в сторе, например при переходе с главной страницы. и если оффер есть — не будем загружать его
если его нет — загрузим

чтобы найти оффер в сторе давай изменим структуру данных, это часто используют для больших приложений

```
offers: { [offerId: string]: Offer}
```
👆🏻такая структура вместо массива

2022-11-23 05:22 UTC, Yustes88 commented on project/src/pages/room/room.tsx
> +  const fullOffers = [...nearbyOffers, offer] as Offers;
если убираю as, то возникает ошибка на стр  145 
по другому у меня не получалось и не получается пока её убрать
![2022-11-23_12-20-57](https://user-images.githubusercontent.com/105499816/203474001-f0eb864d-0125-42fa-b0ef-728552994c5d.png)

2022-11-24 09:21 UTC, yurylavrukhin requested changes
👏🏻

2022-11-24 09:21 UTC, yurylavrukhin commented on project/src/index.tsx
> +store.dispatch(fetchOffersAction());
давай не загружать все офферы на странице оффера

сделаем это в useEffect в компоненте главной страницы — `<Main/>`

2022-11-24 09:21 UTC, yurylavrukhin commented on project/src/store/reducer.ts
> +  offers: [],
```suggestion
  offers: {},
```

2022-11-24 16:21 UTC, yurylavrukhin requested changes

2022-11-24 16:21 UTC, yurylavrukhin commented on project/src/pages/room/room.tsx
> +      store.dispatch(fetchOfferAction(offer));
ошибка если перейти на `/offer/21`

<img width="521" alt="image" src="https://user-images.githubusercontent.com/26966797/203829007-9e22cfe9-6039-4167-a38e-b1393b4ef779.png">

2022-11-24 16:21 UTC, yurylavrukhin commented on project/src/store/selectors.ts
> +}) => Object.values(store.offers).filter(({ id }) => id === offerId)[0];
для поиска элемента в массиве лучше подходит [find](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find)

тогда и возвращаемый тип селектора будет правильный – `OfferType | undefined`

и ошибку в моём соседнем комментарии TS поможет найти
```suggestion
}) => Object.values(store.offers).find(({ id }) => id === offerId);
```

2022-11-25 08:53 UTC, yurylavrukhin requested changes

2022-11-25 08:53 UTC, yurylavrukhin commented on project/src/store/reducer.ts
> +  nearbyOffersList: { [offerId: number]: OfferType};
офферы поблизости мы каждый раз перефетчиваем при переходе на страницу оффера

простого списка здесь достаточно, объект не нужен
```suggestion
  nearbyOffersList: OfferType[];
```

2022-11-25 08:53 UTC, yurylavrukhin commented on project/src/store/reducer.ts
> +  nearbyOffersList: {},
```suggestion
  nearbyOffersList: [],
```

2022-11-25 08:53 UTC, yurylavrukhin commented on project/src/pages/room/room.tsx
сейчас при переходе на страницу оффера я вижу

1. сначала 404
2. затем страничку оффера

хотелось бы сначала видеть состояние загрузки, затем страничку оффера

```suggestion
if (isLoading) {
  return <LoadingSpinner />;
}
```

2022-11-25 14:39 UTC, yurylavrukhin approved these changes
👍

2022-11-25 14:46 UTC, merged