Module7 task2
htmlacademy-react/2069403-six-cities-simple-11 pull request #11
Opened 2022-11-26 11:30 UTC by Yustes88

2022-11-27 13:11 UTC, Yustes88 commented on project/src/components/error-message/error-message.tsx
> +    ? <div className='error-message'>{error}</div>
правильно ли так отображать ошибки?

2022-11-27 13:13 UTC, Yustes88 commented on project/src/browser-history.ts
> +const browserHistory = createBrowserHistory();
после перезагрузки login сохраняется, но информация не отображается
![2022-11-26_20-14-01](https://user-images.githubusercontent.com/105499816/204137114-acd8ab9b-4065-4cf4-90e7-8bbc3cb94a57.png)
![2022-11-26_20-14-16](https://user-images.githubusercontent.com/105499816/204137119-090d411c-87a3-4417-823c-0a752f07c5ef.png)

2022-11-28 09:58 UTC, yurylavrukhin commented on project/src/browser-history.ts
> +const browserHistory = createBrowserHistory();
тут логика должна быть такая:
1. после загрузки приложения отправляем запрос на проверку залогиненности с токеном из куки
2. сервер отвечает данными о пользователе
3. мы склаываем эти данные в redux store
4. вьюшка отображает эти данные 🙂

проверь какой из этапов у тебя отсутствует)

2022-11-28 09:59 UTC, yurylavrukhin commented on project/src/components/error-message/error-message.tsx
> +    ? <div className='error-message'>{error}</div>
1. можно так, 
2. можно показать notification например с https://github.com/fkhadra/react-toastify

2022-11-29 04:32 UTC, yurylavrukhin requested changes
посмотрел проект и ответил с видео в телеграмчике ☺️

2022-11-30 08:31 UTC, yurylavrukhin approved these changes
👏

2022-11-30 08:31 UTC, merged